

# Database - MySQL Cloud Aiven
db.url=jdbc:mysql://mysql-183bc590-daugia2026.a.aivencloud.com:28252/defaultdb?useSSL=true&requireSSL=true
db.user=avnadmin
db.password=YOUR_PASSWORD_HERE

# Connection Pool (S? l??ng k?t n?i ??ng th?i)
db.pool.min=5
db.pool.max=20

# Server
server.port=8080

# Token (H?t h?n sau 24h = 86400000 ms)
token.expiry.ms=86400000